### ISSUE TITLE
Traceback 에러

### ISSUE THREAD

**Issue by Lwnlcks** [chldkato/Tacotron-Korean-Tensorflow2#2]
Traceback (most recent call last):
  File "preprocess.py", line 28, in <module>
    sentence = text_to_sequence(sentence)
  File "F:\Tacotron-Korean-Tensorflow2-master\util\text.py", line 23, in text_to_sequence
    sequence.append(_symbol_to_id[s])
KeyError: '3'

위 같은 에러가
python preprocess.py 를 칠때 나타나는데 어떻해야하나요?

**Comment by chldkato** [comment]
kss 데이터를 사용하셨나요?
